### PR TITLE
fix(lavamoat-node): cli entry args (#1857)

### LINKED ISSUE #344: `lavamoat`: Scrub CLI options from `process.argv` before running script
The LavaMoat node CLI includes its own CLI options, but it leaves them on `process.argv` to be picked up by the script being run by LavaMoat. This could result in them overriding options of the same name intended for the script being run, and it prevents using Yargs "strict mode" where unexpected CLI options are disallowed.

This could be solved by using a CLI delimiter argument like `--`. Treat everything before the `--` as intended for LavaMoat, and everything after as intended for the script being run. This is the same solution that `npm` uses.

See here for the context where this came up: https://github.com/MetaMask/metamask-extension/pull/14836#discussion_r889261864

### PR DESCRIPTION
**Pull request by naugtur**
fix #344

continuation of a contribution from @itsyoboieltr 

todo:
- [x] validate it's needed and correct
- [x] figure out if it's a breaking change and whether we can keep backward-compatibility
- [x] tests
- [x] docs
- [ ] compare with `@lavamoat/node`

### CODE REVIEW

File: packages/lavamoat-node/src/run-command.js [hunk 1]
```diff
@@ -20,18 +20,30 @@ function parseArgs() {
     .usage(
       '$0',
       'lavamoat-run-command [flags for lavamoat] -- command [args for the command]',
-      (yarn) => yargsFlags(yarn, defaults)
+      (yargs) => yargsFlags(yargs, defaults)
```
Comment (naugtur) [inline packages/lavamoat-node/src/run-command.js:23]: lol

File: packages/lavamoat-node/src/run-command.js [hunk 2]
```diff
@@ -20,18 +20,30 @@ function parseArgs() {
...
     )
+    .parserConfiguration({
```
Comment (naugtur) [inline packages/lavamoat-node/src/run-command.js:25]: the old way worked and was doing the same, but this is cleaner and consistent across both files.

File: packages/lavamoat-node/src/cli.js [hunk 3]
```diff
@@ -24,15 +24,24 @@ function parseArgs() {
...
 
-  // patch process.argv so it matches the normal pattern
+  // Rebuild process.argv to pass only entry args
+  const entryArgs = parsedArgs['--']
+  if (!entryArgs) {
+    // patch process.argv so it matches the normal pattern
   // e.g. [runtime path, entrypoint, ...args]
   // we'll use the LavaMoat path as the runtime
   // so we just remove the node path
   process.argv.shift()
```
Comment (naugtur) [inline packages/lavamoat-node/src/cli.js]: I don't remember why we're doing a shift here instead of dropping the second arg, but leaving this in for back comp.

File: packages/lavamoat-node/src/cli.js [hunk 4]
```diff
@@ -24,15 +24,24 @@ function parseArgs() {
...
+  } else {
+    process.argv = [process.argv[0], parsedArgs.entryPath, ...entryArgs]
```
Comment (FrederikBolding) [inline packages/lavamoat-node/src/cli.js:44]:
```suggestion
    // Rebuild process.argv to pass only entry args
    process.argv = [process.argv[0], parsedArgs.entryPath, ...entryArgs]
```
Nit: More readable to place this inline IMO

File: packages/lavamoat-node/src/run-command.js [hunk 5]
```diff
@@ -20,18 +20,30 @@ function parseArgs() {
...
+      'populate--': true,
+    })
     .help()
 
   const parsedArgs = argsParser.parse()
-  const commandName = parsedArgs._[0]
+  const passDownArgs = parsedArgs['--'] || []
```
Comment (FrederikBolding) [inline packages/lavamoat-node/src/run-command.js:31]: Is this not breaking? I don't entirely follow how this is equivalent to the old way

Comment (naugtur) [reply packages/lavamoat-node/src/run-command.js:31]: I think the difference is - in the old version, if you provided some arguments before the -- that were not consumed by lavamoat, they might have been passed on. So this might differ on misuse, but the correct usecase is unaffected.

(also, this cli is somewhat new in comparison and I'm not sure it's been used)

**Review by FrederikBolding — APPROVED** [review]
