### PR TITLE
fix(tofu): parse private names

### LINKED ISSUE #642: lavamoat-tofu Error: unknown ast node type when trying to get name: "PrivateName"
happens when going through @fastify/http-proxy

Error: unknown ast node type when trying to get name: "PrivateName"
    at getNameFromNode (/app/node_modules/lavamoat-tofu/src/util.js:46:11)

### PR DESCRIPTION
**Pull request by boneskull**
This updates `getNameFromNode()` to understand what to do with private names, and also updates `findGlobals()` to ignore private names.

Closes #642

I probably want @kumavis to look at this, because I'm not sure of the intent here.  I'm fairly confident my change in `findGlobals()` is correct, but--what is the name returned by  `getNameForNode()` used for?

### CODE REVIEW

File: packages/tofu/src/util.js [hunk 1]
```diff
@@ -42,7 +42,9 @@ function getNameFromNode (node) {
     return node.name
   } else if (node.type === 'ThisExpression') {
     return 'this'
-  } else {
+  } else if (node.type === 'PrivateName') {
+    return `#${node.id.name}`
+  }else {
```
Comment (legobeat) [inline packages/tofu/src/util.js:47]:
```suggestion
  } else {
```
lint

Comment (boneskull) [reply packages/tofu/src/util.js:47]: ESLint doesn't enforce this.  If we want to worry about it, we should adopt `prettier`.

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* main
  * **PR #678** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/678" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/678?utm_source=stack-comment).

File: packages/tofu/src/util.js (hunk 1 above)
Comment (legobeat) [reply packages/tofu/src/util.js:47]: There is tons of code-style we should try to enforce despite tooling not doing so. Descriptive variable- and function names come to mind.

Tooling like eslint and prettier is valuable but complimentary - not authoritative.

> If we want to worry about it

I don't.

Comment (boneskull) [reply packages/tofu/src/util.js:47]: I'd advocate for them being authoritative--with the goal being eliminating all mention of style issues in PRs.

Comment (naugtur) [reply packages/tofu/src/util.js:47]: I agree with both of you :sweat_smile: 
- machines should do the formatting
- we should do the right thing even if it's possible not to
- some level of automation is great. It stops being great when it gets in the way (eg. prettier demanding some variable names are not in use)
- style comments in PRs are a waste of time
- the reviewer's time is wasted but there's not much the reviewer can do to prevent it

I say we use autoformatting locally even if not enforced. It's what I've been doing and somehow it picked up on the existing config and formatted consistently with the existing code.
Would be great to not have to rely on being lucky like that tho. :) 

Let's close this conversation regardless of outcomes for the PR. I see a branch introducing prettier. Any style conversations can continue there.

Comment (naugtur) [inline packages/tofu/src/util.js:47]:
```suggestion
  } else {
```

**Review by naugtur — APPROVED** [review]
