### PR TITLE
fix: upgrade ses to v1.11.0

### LINKED ISSUE #1578: remove uses of mathTaming and dateTaming from codebase
These lockdown options are deprecated in `ses` and are currently showing warnings.

Currently this affects `@lavamoat/webpack` and `lavamoat-core`.

### PR DESCRIPTION
**Pull request by boneskull**
This upgrades `ses` to v1.11.0.  ~~Nothing more, nothing les.~~

This also resolves #1578, because use of deprecated lockdown options `mathTaming` and `dateTaming` emit warnings. Besides being annoying, they break scenario tests.

### CODE REVIEW

**Comment by boneskull** [comment]
* **#1543** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1543?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#1547](https://github.com/LavaMoat/LavaMoat/pull/1547) <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1547?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#1593](https://github.com/LavaMoat/LavaMoat/pull/1593) <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1593?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#1588** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1588?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1573** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1573?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1573?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by boneskull** [comment]
Needs #1578

File: packages/core/src/kernelTemplate.js [hunk 1]
```diff
@@ -52,11 +52,7 @@
     ;templateRequire('ses')
 
     const lockdownOptions = {
-      // gives a semi-high resolution timer
-      dateTaming: 'unsafe',
       // this is introduces non-determinism, but is otherwise safe
```
Comment (naugtur) [inline packages/core/src/kernelTemplate.js]: This line needs to go too.


```suggestion

```

File: packages/core/src/kernelTemplate.js [hunk 2]
```diff
@@ -52,11 +52,7 @@
...
-      mathTaming: 'unsafe',
-      // lets code observe call stack, but easier debuggability
```
Comment (naugtur) [inline packages/core/src/kernelTemplate.js:59]: This line needs to stay, it's a comment on errorTaming

**Review by naugtur — APPROVED** [review]

**Comment by leotm** [comment]
should we also remove

https://github.com/LavaMoat/LavaMoat/blob/fb0bf19323cc9552df1ed7f87d17bd09bd702c70/packages/webpack/src/plugin.js#L760-L761

**Review by leotm — APPROVED** [review]

**Comment by boneskull** [comment]
@leotm Good catch.  I changed the code in `plugin.js` to just import `LockdownOptions` from `ses`, since we can do that. I think the fact that `LockdownOptions` was copied was probably due to an old TS bug in `ses` that I fixed.

**Comment by boneskull** [comment]
ref: #1134
