### PR TITLE
fix(node): allow flags to be passed to entrypoint

### LINKED ISSUE #1504: @lavamoat/node: no way to pass arguments to an entrypoint
Example

1. create a file
3. `yarn lavamoat file.js -flag`

Example 2

1. create a file
2. `yarn lavamoat file.js -- -flag`

Result

`notice  › Unknown arguments: f, l, a, g`

Note

usual `lavamoat` flags with no entrypoint like `--help` and `--version` work as expected

### PR DESCRIPTION
**Pull request by boneskull**
This ensures that options and positional arguments may be passed into the entrypoint module from the command line. Such args must be provided after `--`.

`@lavamoat/node` attempts to erase itself from `process.argv` before execution, which may be right or may be wrong.

Closes #1504

### CODE REVIEW

**Comment by boneskull** [comment]
* **#1506** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1506?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1506?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: packages/node/src/cli.js [hunk 1]
```diff
@@ -62,6 +51,52 @@ const PATH_GROUP = 'Path Options:'
...
+ *
+ * For this to work, we _must_ mutate `process.argv` _in place_.
+ *
+ * @param {string} entrypoint Entry module
+ * @param {(string | number)[]} nonOptionArguments Array of stuff passed after
+ *   `--` on the command-line. Note that Yargs parses numbers, and we have to
+ *   convert them back to strings.
+ * @returns {void}
+ */
+const stripProcessArgv = (entrypoint, nonOptionArguments = []) => {
```
Comment (naugtur) [inline packages/node/src/cli.js:69]: Not sure how necessary this is, but definitely nice to have.

**Review by naugtur — APPROVED** [review]
